version: "3"

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_DB: 'dev'
      POSTGRES_SCHEMA: 'dev'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypass'
    expose:
      - "5432"
    ports:
      - "5432:5432"

  vehicle:
    build: "./vehicle"
    container_name: "vehicle"
    environment:
      DB_NAME: 'dev'
      DB_SERVICE: 'postgres'
      DB_PORT: 5432
      DB_SCHEMA: 'dev'
      DB_USER: 'myuser'
      DB_PASSWORD: 'mypass'
      DB_TABLE: 'vehicle'
    expose:
      - "5000"
    ports:
      - "5000:5000"
    links:
      - postgres

